version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: zipitda_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zipitda_db        # 프로젝트 DB명
      MYSQL_USER: zipitda_user          # 일반 사용자 계정
      MYSQL_PASSWORD: password1234      # 일반 사용자 비밀번호
      TZ: "Asia/Seoul"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--lower_case_table_names=1"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: zipitda_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: