version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zipitda
      MYSQL_USER: zipitda_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --protected-mode no  # 외부 접속 허용
    networks:
      - app_network

  app:
    build: .
    container_name: zipitda_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zipitda?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: zipitda_user
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_REDIS_HOST: redis  # Redis 컨테이너 이름으로 설정
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: