spring:
  application:
    name: zipitda

  # 서버 포트 (Docker 사용 시 8081로 변경)
  server:
    port: 8081

  # MySQL 데이터베이스 설정 (Docker 환경에서 사용)
  datasource:
    url: jdbc:mysql://localhost:3306/zipitda_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: zipitda_user
    password: password1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 설정 (Docker 환경에서 사용)
  data:
    redis:
      host: localhost
      port: 6379

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

  # MyBatis 설정
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30

  # 메일 인증 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: itda.devlab@gmail.com
    password: rafy nucj zzoa sbzt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # Swagger UI 설정
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

# 로그 레벨 설정
logging:
  level:
    org.mybatis: DEBUG
    org.springframework: DEBUG

# 소셜 로그인 설정
kakao:
  client-id: cce91e98d45c184b6a3f3d314a6d5d0b
  client-secret: 7Ah86QzRyGZnrKQXMgl3UKs1fiaBxptZ
  redirect-uri: http://localhost:8081/social-login/kakao/callback
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

naver:
  client-id: YOUR_NAVER_CLIENT_ID
  client-secret: YOUR_NAVER_CLIENT_SECRET
  redirect-uri: http://localhost:8081/social-login/naver/callback
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me